"""
app/integrations/telegram/services/vector_mutation.py

[ADDITIVE] Vector mutation abstraction for Telegram content.

Wraps ChromaDB's collection.delete() and collection.upsert() operations
behind a typed, testable interface. All vector IDs are deterministic
(generated by KnowledgeObject.vector_document_id).

ChromaDB 1.5.9:
  - collection.add() with existing ID = upsert (overwrite)
  - collection.delete(ids=[...]) = bulk delete by ID
  - collection.delete(where={...}) = delete by metadata filter
    (used for source_message_id-based bulk deletion)
"""

from __future__ import annotations

import logging
from typing import Any

import chromadb

logger = logging.getLogger(__name__)


class VectorChunk:
    """A single vector chunk ready for ChromaDB insertion."""
    __slots__ = ("vector_id", "text", "embedding", "metadata")

    def __init__(
        self,
        vector_id: str,
        text: str,
        embedding: list[float],
        metadata: dict[str, Any],
    ) -> None:
        self.vector_id = vector_id
        self.text = text
        self.embedding = embedding
        self.metadata = metadata


class VectorMutationService:
    """
    Typed, idempotent wrapper around ChromaDB mutation operations.

    All operations are safe to call multiple times:
    - upsert_chunks: same ID = overwrite, new ID = insert
    - delete_by_vector_ids: missing IDs are silently skipped
    - delete_by_source_message: uses metadata filter, handles 0-result gracefully

    Does NOT require unfiltered collection.get() (avoids the known hang
    in PersistentClient when collection is large).
    """

    def __init__(self, collection: chromadb.Collection) -> None:
        self._col = collection

    def upsert_chunks(self, chunks: list[VectorChunk]) -> int:
        """
        Upsert a list of VectorChunks into ChromaDB.
        Existing IDs are overwritten (Strategy C — DR-3).
        Returns count of chunks upserted.
        """
        if not chunks:
            return 0
        self._col.upsert(
            ids=[c.vector_id for c in chunks],
            embeddings=[c.embedding for c in chunks],
            documents=[c.text for c in chunks],
            metadatas=[c.metadata for c in chunks],
        )
        logger.debug("VectorMutationService: upserted %d chunks", len(chunks))
        return len(chunks)

    def delete_by_vector_ids(self, vector_ids: list[str]) -> int:
        """
        Delete specific vector IDs from ChromaDB.
        Missing IDs are silently ignored (idempotent).
        Returns count of IDs passed (ChromaDB doesn't return actual deleted count).
        """
        if not vector_ids:
            return 0
        # ChromaDB delete with IDs that don't exist is a no-op
        self._col.delete(ids=vector_ids)
        logger.debug(
            "VectorMutationService: deleted_requested=%d vector IDs", len(vector_ids)
        )
        return len(vector_ids)

    def get_by_vector_ids(self, vector_ids: list[str]) -> list[VectorChunk]:
        """
        Fetch existing chunks from ChromaDB by their vector IDs.
        Silently ignores missing IDs.
        """
        if not vector_ids:
            return []
            
        try:
            result = self._col.get(
                ids=vector_ids,
                include=["embeddings", "documents", "metadatas"]
            )
            
            ids = result.get("ids", [])
            embeddings = result.get("embeddings") or []
            documents = result.get("documents") or []
            metadatas = result.get("metadatas") or []
            
            chunks = []
            for i in range(len(ids)):
                chunks.append(VectorChunk(
                    vector_id=ids[i],
                    text=documents[i] if i < len(documents) else "",
                    embedding=embeddings[i] if i < len(embeddings) else [],
                    metadata=metadatas[i] if i < len(metadatas) else {},
                ))
            return chunks
        except Exception as exc:
            logger.warning(
                "VectorMutationService: get_by_vector_ids failed: %s", exc
            )
            return []

    def delete_by_source_message(
        self,
        owner_id: str,
        source: str,
        source_account_id: str,
        conversation_id: str,
        source_message_id: str,
    ) -> int:
        """
        Delete ALL vectors for a specific source message using metadata filter.
        Returns count of IDs found and deleted (via get→delete pattern).

        Uses filtered get() rather than unfiltered scan to avoid the
        PersistentClient hang known in ChromaDB 1.5.9.
        """
        where = {
            "$and": [
                {"owner_id": {"$eq": owner_id}},
                {"source": {"$eq": source}},
                {"source_account_id": {"$eq": source_account_id}},
                {"conversation_id": {"$eq": conversation_id}},
                {"source_message_id": {"$eq": source_message_id}},
            ]
        }
        try:
            result = self._col.get(where=where, include=[])
            ids = result.get("ids", [])
            if ids:
                self._col.delete(ids=ids)
                logger.info(
                    "VectorMutationService: deleted %d vectors for msg=%r conv=%r",
                    len(ids), source_message_id, conversation_id,
                )
            return len(ids)
        except Exception as exc:
            logger.warning(
                "VectorMutationService: delete_by_source_message failed msg=%r: %s",
                source_message_id, exc,
            )
            raise
