name: Security Scanning

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays at midnight

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Fail the workflow on critical/high vulnerabilities
